# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13.5 # Specify the version of the image
    restart: always # Restart the container if it fails
    environment: # Set the username and password for the database
      - POSTGRES_USER=recipe 
      - POSTGRES_PASSWORD=RecipePassword
    volumes: # Mount the volume to persist the data even if the container is stopped or removed
      - postgres:/var/lib/postgresql/data
    ports: # Expose the port to access the database
      - '5432:5432'
volumes:
  postgres: 